DomainAnalyzer/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.views.generic.base import RedirectView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('domains/', include('domains.urls')),  # Include app URLs
    path('', RedirectView.as_view(url = 'http://127.0.0.1:8000/domains/analyze/')),
]

domains/urls.py
from django.urls import path
from . import views

app_name = 'domains'  # Add this line to avoid namespace conflicts

urlpatterns = [
    path('analyze/', views.analyze_domain, name='analyze_domain'),
    path('phase2/', views.phase2_domain, name='phase2_domain'),
]

domains/models.py
from django.db import models
from django.utils import timezone

class DomainAnalysis(models.Model):
    domain = models.CharField(max_length=255)
    public_ip = models.CharField(max_length=15)
    http_status = models.PositiveIntegerField(null=True, blank=True)
    https_status = models.PositiveIntegerField(null=True, blank=True)
    timestamp = models.DateTimeField(default=timezone.now) 

     
    def __str__(self):
        return self.domain

class Results(models.Model):
    domain = models.CharField(max_length=100)
    Public_ip = models.CharField(max_length=100)
    status_code_if_redirected = models.CharField(max_length=100,null=True,blank=True)
    http_status = models.CharField(max_length=100)
    https_redirect_url = models.CharField(max_length=100,null=True,blank=True)
    https_status = models.CharField(max_length=100)
    timestamp = models.DateTimeField(default=timezone.now) 
    
    
    # http_final_url = models.CharField(max_length=100)
    # http_public_ip = models.CharField(max_length=100)
   
    
    # https_final_url = models.CharField(max_length=100)
    # https_public_ip = models.CharField(max_length=100)
    # remarks = models.CharField(max_length=100)
        



domains/views.py
from django.shortcuts import render
import requests
from django.conf import settings
from bs4 import BeautifulSoup
from domains.models import DomainAnalysis
import socket
import time
from django.utils import timezone
from django.http import JsonResponse
from .models import Results

def is_non_existent_domain(domain):
    try:
        socket.gethostbyname(domain)
        return False  
    except socket.gaierror:
        return True  

def is_matching_pattern(domain):
    return domain.startswith("164.10")


def analyze2_single_domain(domain):

    http_public_ip = get_public_ip(domain)
    
   
    if http_public_ip == "Non-Existent Domain":
        return {
            'domain': domain,
            'http_status': 'Filtered Out',
            'http_redirect_url': 'N/A',
            'http_final_url': 'N/A',
            'http_public_ip': 'N/A',
            'https_status': 'Filtered Out',
            'https_redirect_url': 'N/A',
            'https_final_url': 'N/A',
            'https_public_ip': 'N/A',
            'remarks': "Non-Existent Domain",
        }
    
    
    if not http_public_ip.startswith("164.100"):
        return {
            'domain': domain,
            'http_status': 'Filtered Out',
            'http_redirect_url': 'N/A',
            'http_final_url': 'N/A',
            'http_public_ip': 'N/A',
            'https_status': 'Filtered Out',
            'https_redirect_url': 'N/A',
            'https_final_url': 'N/A',
            'https_public_ip': 'N/A',
            'remarks': "Public IP does not start with 164.100",
        }


    try:
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
        }

        http_status = https_status = None 

        http_public_ip = get_public_ip(domain)
        https_public_ip = get_public_ip(domain)

        http_url = "http://" + domain
        try:
            http_response = requests.get(http_url, allow_redirects=False, timeout=5, headers=headers, verify=False)
            http_status = http_response.status_code
            http_final_url = http_url
            http_redirect_url = None

            if http_status in {301, 302}:
                http_redirect_url = http_response.headers.get('Location')

                http_public_ip = get_public_ip(domain)
                http_final_url = http_redirect_url
        except requests.RequestException:
            http_status = 'Some Error'
            http_final_url = 'N/A'
            http_redirect_url = 'N/A'

        https_url = "https://" + domain
        try:
            https_response = requests.get(https_url, allow_redirects=False, timeout=5, headers=headers, verify=False)
            https_status = https_response.status_code
            https_final_url = https_url
            https_redirect_url = None

            if https_status in {301, 302}:
                https_redirect_url = https_response.headers.get('Location')

                https_public_ip = get_public_ip(domain)
                https_final_url = https_redirect_url
        except requests.RequestException:
            https_status = 'Some Error'
            https_final_url = 'N/A'
            https_redirect_url = 'N/A'

        if http_status in {403, 404, 500}:
            return {
                'domain': domain,
                'http_status': http_status,
                'http_redirect_url': 'N/A',
                'http_final_url': 'N/A',
                'http_public_ip': 'N/A',
                'https_status': 'Filtered Out',
                'https_redirect_url': 'N/A',
                'https_final_url': 'N/A',
                'https_public_ip': 'N/A',
                'remarks': "HTTP Status Code is 403, 404, or 500",
            }

       

        analysis_result = {
            'domain': domain,
            'http_status': http_status,
            'http_redirect_url': http_redirect_url,
            'http_final_url': http_final_url,
            'http_public_ip': http_public_ip,
            'https_status': https_status,
            'https_redirect_url': https_redirect_url,
            'https_final_url': https_final_url,
            'https_public_ip': https_public_ip,
            'remarks': "Success",
        }
        
        obj1 = Results(
            domain=domain,
            Public_ip=http_public_ip,
            status_code_if_redirected=http_redirect_url,
            http_status=http_status,
            https_redirect_url=https_redirect_url,
            https_status=https_status,
        )
        obj1.save()
        
        print(analysis_result)
        return analysis_result

        return JsonResponse(analysis_result)
    except requests.RequestException:
        return {
            'domain': domain,
            'http_status': 'Some Error',
            'http_redirect_url': 'N/A',
            'http_final_url': 'N/A',
            'http_public_ip': 'N/A',
            'https_status': 'Some Error',
            'https_redirect_url': 'N/A',
            'https_final_url': 'N/A',
            'https_public_ip': 'N/A',
            'remarks': "Error fetching data",
        }

def phase2_domain(request):
    
    if 'analysis_results' in request.session:
        
        analysis_results = request.session['analysis_results']

       
        filtered_status_codes = [403, 404, 500]
        filtered_results = []

        for result in analysis_results:
            http_public_ip = result.get('http_public_ip', '')
            https_public_ip = result.get('https_public_ip', '')

            
            if http_public_ip.startswith("164.10") :
               
                if result['http_status'] not in filtered_status_codes and result['https_status'] not in filtered_status_codes:
                    filtered_results.append(result)

        return render(request, 'phase2.html', {'filtered_results': filtered_results})



    return render(request, 'upload.html')

def get_public_ip(domain ):
    try:
        ip_address = socket.gethostbyname(domain)
        return (ip_address)
    except:
        return str("Non-Existent Domain")



def analyze_single_domain(domain):
    try:
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
        }

        
        http_public_ip = get_public_ip(domain)
        https_public_ip = get_public_ip(domain)

       
        http_url = "http://" + domain
        try:
            http_response = requests.get(http_url, allow_redirects=False, timeout=5, headers=headers, verify=False)
            http_status = http_response.status_code
            http_final_url = http_url
            http_redirect_url = None
            
            if http_status in {301, 302}:
                http_redirect_url = http_response.headers.get('Location')
               
                http_public_ip = get_public_ip(domain)
                http_final_url = http_redirect_url
        except requests.RequestException:
            http_status = 'Some Error'
            http_final_url = 'N/A'
            http_redirect_url = 'N/A'
        
       
        https_url = "https://" + domain
        try:
            https_response = requests.get(https_url, allow_redirects=False, timeout=5, headers=headers, verify=False)
            https_status = https_response.status_code
            https_final_url = https_url
            https_redirect_url = None
            
            if https_status in {301, 302}:
                https_redirect_url = https_response.headers.get('Location')
               
                https_public_ip = get_public_ip(domain)
                https_final_url = https_redirect_url
        except requests.RequestException:
            https_status = 'Some Error'
            https_final_url = 'N/A'
            https_redirect_url = 'N/A'
        
        analysis_result = {
            'domain': domain,
            'http_status': http_status,
            'http_redirect_url': http_redirect_url, 
            'http_final_url': http_final_url,
            'http_public_ip': http_public_ip, 
            'https_status': https_status,
            'https_redirect_url': https_redirect_url, 
            'https_final_url': https_final_url,
            'https_public_ip': https_public_ip,  
            'remarks': "Success",
        }
        obj1 = Results(
            domain=domain,
            Public_ip= http_public_ip,
            status_code_if_redirected= http_redirect_url,
            http_status = http_status,
            https_redirect_url= https_redirect_url,
            https_status= https_status)
            # timestamp=timezone  )
            # http_final_url=http_final_url
            
            
            
            # https_final_url= https_final_url,
            # https_public_ip= https_public_ip,  
            # remarks= "Success")
        obj1.save() 
    
        print(analysis_result)
        return analysis_result

    except requests.RequestException:
       
        return {
            'domain': domain,
            'http_status': 'Some Error',
            'http_redirect_url': 'N/A',
            'http_final_url': 'N/A',
            'http_public_ip': 'N/A',
            'https_status': 'Some Error',
            'https_redirect_url': 'N/A',
            'https_final_url': 'N/A',
            'https_public_ip': 'N/A',
            'remarks': "Error fetching data",
        }

def process_analysis_result(analysis_result):
    
    http_status = analysis_result['http_status']
    https_status = analysis_result['https_status']
    
    if http_status >= 400 and https_status >= 400:

domains/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

domains/templates/phase2.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Phase Two Results</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- End model css here -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap4.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap4.min.js"></script>

     <!-- Here we add css for datatable -->
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.3/css/buttons.dataTables.min.css">
    <script src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>

    <style>
    .custom-table {
        border-collapse: collapse;
        width: 100%;
    }

    .custom-table th,
    .custom-table td {
        border: 1px solid #ccc;
        padding: 8px;
        text-align: left;
    }

    .custom-table th {
        background-color: #f5f5f5;
    }
</style>
</head>
<body>
<div class="container">
    <h1>Domain Analysis Results - Filtered</h1>
    <table id="example" class="custom-table">
        <thead>
        <tr>
            <th>Domain</th>
            <th>Public IP</th>
            <th>Status Code if redirected</th>
            <th>HTTP Status</th>
            <th>HTTPS Redirect Url</th>
            <th>HTTPS Status</th>
        </tr>
        </thead>
        <tbody class="table-body">
        {% for result in filtered_results %}
        {% if result.http_status != 'Filtered Out' and result.https_status != 'Filtered Out' and result.http_status != 'Some Error' and result.https_status != 'Some Error' %}
        <tr>
            <td>{{ result.domain }}</td>
            <td>{{ result.http_public_ip }}</td>
            <td>{{ result.http_redirect_url }}</td>
            <td>{{ result.http_status }}</td>
            <td>{{ result.https_redirect_url }}</td>
            <td>{{ result.https_status }}</td>
        </tr>
        
        {% endif %}
        {% endfor %}
        </tbody>
    </table>

    

</div>

<script>
    $(document).ready(function () {
        $('#example').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    });
</script>

</body>
</html>

domains/templates/result.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Domain Analysis Results</title>
    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- End model css here -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap4.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap4.min.js"></script>

     <!-- Here we add css for datatable -->
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.3/css/buttons.dataTables.min.css">
    <script src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>

    <style>
    .custom-table {
        border-collapse: collapse;
        width: 100%;
    }

    .custom-table th,
    .custom-table td {
        border: 1px solid #ccc;
        padding: 8px;
        text-align: left;
    }

    .custom-table th {
        background-color: #f5f5f5;
    }
</style>

</head>
<body>
<div class="container">
    <h1>Domain Analysis Results</h1>
    <table id="example" class="custom-table">
        <thead>
        <tr>
            <th>Domain</th>
            <th>Public IP</th>
            <th>Status Code if redirected</th>
            <th>HTTP Status</th>
            <th>HTTPS Redirect Url</th>
            <th>HTTPS Status</th>
        </tr>
        </thead>
        <tbody>
        {% for result in results %}
        <tr>
            <td>{{ result.domain }}</td>
            <td>{{ result.http_public_ip }}</td>
            <td>{{ result.http_redirect_url }}</td>
            <td>{{ result.http_status }}</td>
            <td>{{ result.https_redirect_url }}</td>
            <td>{{ result.https_status }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'domains:phase2_domain' %}" target="_blank">GO TO PHASE 2 </a>
    <!-- <a href="{% url 'domains:phase2_domain' %}" >GO TO PHASE 2 </a> -->

</div>

<script>
    $(document).ready(function () {
        $('#example').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    });
</script>

</body>
</html>





domains/templates/upload.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <style>
    .formdata{
        background-color: gray;
    }
  </style>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Domain Analyser</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="result.html">Processed Data <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="#">Filetered Data (NICNET) <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="#">Assignment<span class="sr-only">(current)</span></a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
           
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
      <div class="container mt-4">
          <h4 class="text-success text-center mt-4">Domain Analyzer</h4>
        <div class="bg-light mt-4" style="width:50%; margin-left:25%; ">
            
    
                <div class="form-group">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                <label for="exampleFormControlFile1" class="text-primary">Please upload the .txt file</label>
                <input type="file" name="domain_list" accept=".txt" required>
                <!-- <button type="submit" class="btn btn-sm btn-outline-light">Analyze Domains</button> -->
                <button type="submit" class="btn btn-primary mb-4 text-light" style="width:60%; margin-left:17%; border:2px solid white; margin-bottom:12px; ">Analyze Domains</button>
                </div>
              </form>
        </div>
<!--         
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="domain_list" accept=".txt">
            <button type="submit">Analyze Domains</button>
        </form> -->
      </div>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->
  </body>
</html>